ElectionSystem_RWA/Models/Voter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElectionSystem_RWA.Models
{
    public class Voter
    {
        public int Id { get; set; }
        public string President { get; set; }
        public string VicePresident { get; set; }
        public string Secretary { get; set; }
        public string Treasure { get; set; }
        public string Member1 { get; set; }
        public string Member2 { get; set; }
        public string Member3 { get; set; }
        public string Member4 { get; set; }
        public string Member5 { get; set; }
        public string Member6 { get; set; }
        public Unit Unit { get; set; }
        public int UnitId { get; set; }
    }
}

ElectionSystem_RWA/Controllers/VotersController.cs
using ElectionSystem_RWA.Models;
using ElectionSystem_RWA.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
namespace ElectionSystem_RWA.Controllers
{
    public class VotersController : Controller
    {
        private ApplicationDbContext dbContext;
        public VotersController()
        {
            dbContext = new ApplicationDbContext();
        }
        // GET: Voters
      
            [HttpGet]
        public ActionResult Ballot()
        {
            var viewModel = new PostingViewModel();
            viewModel.President = dbContext.Presidents.Include(p=>p.Qualification).ToList();
            viewModel.VicePresident=dbContext.VicePresident.Include(p => p.Qualification).ToList();
            viewModel.Secretary= dbContext.Secretary.Include(p => p.Qualification).ToList();
            viewModel.Treasurer = dbContext.Treasurer.Include(p => p.Qualification).ToList();
            viewModel.Members = dbContext.Members.Include(p => p.Qualification).ToList();
            
            return View(viewModel);
        }
       
        public ActionResult CountVote(int id)
        {
           
            var president=dbContext.Presidents.FirstOrDefault(p => p.Id == id);
            president.Vote++;
            dbContext.SaveChanges();
            //count++;
            return View("Thank");
        }
        public ActionResult Result()
        {
            var president = dbContext.Presidents.ToList();

            //ViewBag.president = president;

            return View(president);
        }
        public ActionResult Winner()
        {
            var president = dbContext.Presidents.OrderByDescending(p=>p.Vote).First();
            return View(president);
        }
        //[HttpPost]
        //public ActionResult Ballot(PostingViewModel voteFromView)
        //{
        //    if(!ModelState.IsValid)
        //    {
        //        var viewModel = new PostingViewModel();
        //        viewModel.President = dbContext.Presidents.Include(p => p.Qualification).ToList();
        //        viewModel.VicePresident = dbContext.VicePresident.Include(p => p.Qualification).ToList();
        //        viewModel.Secretary = dbContext.Secretary.Include(p => p.Qualification).ToList();
        //        viewModel.Treasurer = dbContext.Treasurer.Include(p => p.Qualification).ToList();
        //        viewModel.Members = dbContext.Members.Include(p => p.Qualification).ToList();
        //        return View(viewModel);
        //    }
        //   voteFromView.President.
        //    dbContext.Presidents.Add();
        //    return View("Thank");
        //}
       
        public ActionResult Thank()
        {
            return View();
        }
    }
}

ElectionSystem_RWA/Views/Voters/Ballot.cshtml
@model ElectionSystem_RWA.ViewModels.PostingViewModel
@{
    ViewBag.Title = "Ballot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CountVote","Voters"))
{
    <h3>VOTE FOR PRESIDENT</h3>
    <table class="table table-primary">
        <tr>
            <th>Candidate Name</th>
            <th>Current Occupation</th>
            <th>Previous RWA Member</th>
            <th>Part Of Govt/Police/NGO</th>
            <th>Criminal Record</th>
            <th>Qualification</th>
            <th>Vote</th>
        </tr>

        @foreach (var item in Model.President)
        {
            <tr>
                <td>@item.CandidateName</td>
                <td>@item.CurrentOccupation</td>
                <td>@item.PreviousRWAMember</td>
                <td>@item.PartOfGovtPoliceNGO</td>
                <td>@item.CriminalRecord</td>
                <td>@item.Qualification.QualificationType</td>
                
                <td>@Html.ActionLink("Vote","CountVote","Voters",new { id=item.Id},new { @class="btn btn-primary"})</td>
            </tr>
        }
        
    </table>
    @*@Html.DropDownListFor(p=>p.President,ViewBag.Presidents as SelectList, null, htmlAttributes: new { @class = "form-control" })
    <input type="submit"value="Vote"class="btn btn-primary" />*@
}
    @*<h3>VOTE FOR VICEPRESIDENT</h3>
        <table  class="table table-primary">
            <tr>
                <th>Candidate Name</th>
                <th>Current Occupation</th>
                <th>Previous RWA Member</th>
                <th>Part Of Govt/Police/NGO</th>
                <th>Criminal Record</th>
                <th>Qualification</th>
                <th>Choose</th>
            </tr>
            <tr>
                @foreach (var item in Model.VicePresident)
                {
                    <td>@item.CandidateName</td>
                    <td>@item.CurrentOccupation</td>
                    <td>@item.PreviousRWAMember</td>
                    <td>@item.PartOfGovtPoliceNGO</td>
                    <td>@item.CriminalRecord</td>
                    <td>@item.Qualification.QualificationType</td>
                    <td></td>
                }
            </tr>
        </table>
        <h3>VOTE FOR SECRETARY</h3>
        <table class="table table-primary">
            <tr>
                <th>Candidate Name</th>
                <th>Current Occupation</th>
                <th>Previous RWA Member</th>
                <th>Part Of Govt/Police/NGO</th>
                <th>Criminal Record</th>
                <th>Qualification</th>
                <th>Choose</th>
            </tr>
            <tr>
                @foreach (var item in Model.Secretary)
                {
                    <td>@item.CandidateName</td>
                    <td>@item.CurrentOccupation</td>
                    <td>@item.PreviousRWAMember</td>
                    <td>@item.PartOfGovtPoliceNGO</td>
                    <td>@item.CriminalRecord</td>
                    <td>@item.Qualification.QualificationType</td>
                    <td>Choose</td>
                }
            </tr>
        </table>
        <h3>TREASURER</h3>
        <table class="table table-primary">
            <tr>
                <th>Candidate Name</th>
                <th>Current Occupation</th>
                <th>Previous RWA Member</th>
                <th>Part Of Govt/Police/NGO</th>
                <th>Criminal Record</th>
                <th>Qualification</th>
                <th>Choose</th>
            </tr>
            <tr>
                @foreach (var item in Model.Treasurer)
                {
                    <td>@item.CandidateName</td>
                    <td>@item.CurrentOccupation</td>
                    <td>@item.PreviousRWAMember</td>
                    <td>@item.PartOfGovtPoliceNGO</td>
                    <td>@item.CriminalRecord</td>
                    <td>@item.Qualification.QualificationType</td>
                    <td></td>
                }
            </tr>
        </table>
        <h3>VOTE FOR MEMBERS</h3>
        <table class="table table-primary">
            <tr>
                <th>Candidate Name</th>
                <th>Current Occupation</th>
                <th>Previous RWA Member</th>
                <th>Part Of Govt/Police/NGO</th>
                <th>Criminal Record</th>
                <th>Qualification</th>
                <th>Choose</th>
            </tr>
            <tr>
                @foreach (var item in Model.Members)
                {
                    <td>@item.CandidateName</td>
                    <td>@item.CurrentOccupation</td>
                    <td>@item.PreviousRWAMember</td>
                    <td>@item.PartOfGovtPoliceNGO</td>
                    <td>@item.CriminalRecord</td>
                    <td>@item.Qualification.QualificationType</td>
                    <td></td>
                }
            </tr>
        </table>*@

ElectionSystem_RWA/Views/Voters/Result.cshtml
@model IEnumerable<ElectionSystem_RWA.Models.President>
@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Voting Result</h2>

<br />
<table class="table table-primary">
    <thead>
        <tr>
            <th>Candidate Name</th>
            <th>Vote Count</th>
        </tr>
    </thead>
    
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.CandidateName</td>
                <td>@item.Vote</td>
            </tr>
        }
    </tbody>
    

</table>
@Html.ActionLink("To view the winner","Winner","Voters")

ElectionSystem_RWA/Views/Voters/Thank.cshtml
@{
    ViewBag.Title = "Thank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h2>Thank You for Voting</h2>
</div>

ElectionSystem_RWA/Views/Voters/Winner.cshtml
@model ElectionSystem_RWA.Models.President
@{
    ViewBag.Title = "Winner";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:green">Winner of president election : @Model.CandidateName</h2>